# Generated by Django 4.2.11 on 2024-03-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Department', models.CharField(max_length=30)),
                ('Pic', models.ImageField(upload_to='static/img/doctors/')),
                ('Qualification', models.CharField(max_length=30)),
                ('PhoneNo', models.BigIntegerField()),
            ],
        ),
    ]
